apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dauv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dauv
    app.kubernetes.io/part-of: hypershift-test
  name: devfile-sample-dauv
  namespace: dfodor-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-dauv
status:
  loadBalancer: {}
